[build]
  ignore = "1"
  base = "pancake-swap-interface-v1"
  publish = "pancake-swap-interface-v1/build"
  command = ""

[build.environment]
  REACT_APP_CHAIN_ID = "97"
  REACT_APP_GTAG = "GTM-PXLD3XW"
  REACT_APP_NETWORK_URL = "https://data-seed-prebsc-1-s1.binance.org:8545"
  